---
- name: "Template Elasticsearch instances file"
  template:
    src: "instances_elasticsearch.yml.j2"
    dest: "/usr/share/elasticsearch/instances_elasticsearch.yml"
  when: certificates.elasticsearch.generate

- name: "Template Logstash instances file"
  template:
    src: "instances_logstash.yml.j2"
    dest: "/usr/share/elasticsearch/instances_logstash.yml"
  when: certificates.logstash.generate
