---
- name: "Convert CA key into pem format"
  command: |
    openssl rsa \
    -in {{ ca.dir }}/{{ ca.key.file }} \
    -passin pass:'{{ ca.key.pass }}' \
    -aes256 \
    -passout pass:'{{ ca.key.pass }}'
    -out {{ ca.dir }}/{{ ca.key.file | regex_replace('.key', '-key.pem') }}

- name: "Create elasticsearch certificates with elasticsearch-certutil"
  command: >
    /usr/share/elasticsearch/bin/elasticsearch-certutil cert \
    --ca-key {{ ca.dir }}/{{ ca.key.file | regex_replace('.key', '-key.pem') }} \
    --ca-cert {{ ca.dir }}/{{ ca.cert.file }} \
    --ca-pass '{{ ca.key.pass }}' \
    --silent \
    -in instances_elasticsearch.yml \
    --pass '{{ certificates.elasticsearch.pass }}' \
    -out {{ ca.dir }}/elasticsearch-certificates.zip
